kind: Template
apiVersion: v1
parameters:
  - name: NAME
  - name: USERNAME
    value: elastic
#    generate: expression
#    from: admin-[a-zA-Z0-9]{6}
  - name: PASSWORD
    generate: expression
    from: '[a-zA-Z]{1}[a-zA-Z0-9]{20}[a-zA-Z]{1}'
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${NAME}
  stringData:
    username: ${USERNAME}
    password: ${PASSWORD}