kind: Template
apiVersion: v1
parameters:
  - name: NAME
    required: true
  - name: ENCRYPTION_KEY
    generate: expression
    from: '[a-zA-Z]{1}[a-zA-Z0-9]{48}[a-zA-Z]{1}'
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${NAME}
  stringData:
    encryptionkey: ${ENCRYPTION_KEY}