---

elasticsearchHosts: "https://security-master:9200"

podSecurityContext:
  fsGroup: null

securityContext:
  runAsUser: null

extraEnvs:
  - name: 'ELASTICSEARCH_USERNAME'
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: username
  - name: 'ELASTICSEARCH_PASSWORD'
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: password
  - name: 'KIBANA_ENCRYPTION_KEY'
    valueFrom:
      secretKeyRef:
        name: kibana
        key: encryptionkey

kibanaConfig:
  kibana.yml: |
    server.ssl:
      enabled: false
      #key: /usr/share/kibana/config/certs/elastic-certificate.pem
      #certificate: /usr/share/kibana/config/certs/elastic-certificate.pem
      #clientAuthentication: optional
    xpack.security.encryptionKey: ${KIBANA_ENCRYPTION_KEY}
    xpack.security.authc.providers: [basic]
    elasticsearch.username: "${ELASTICSEARCH_USERNAME}"
    elasticsearch.password: "${ELASTICSEARCH_PASSWORD}"
    elasticsearch.ssl:
      certificateAuthorities: /usr/share/kibana/config/certs/elastic-certificate.pem
      verificationMode: certificate

protocol: http

secretMounts:
  - name: elastic-certificate-pem
    secretName: elastic-certificate-pem
    path: /usr/share/kibana/config/certs