apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: jenkins
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: ${NAME}-base
  spec:
    lookupPolicy:
      local: false
    tags:
    - name: v1
      from:
        kind: ImageStreamImage
        name: jenkins-atomic@sha256:c7cbf7704ce0b8b53e3549c42aa636566eca4b4da179734b6794f890a9838a3d
      importPolicy: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: ${NAME}
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    name: ${NAME}${SUFFIX}
  spec:
    failedBuildsHistoryLimit: 2 
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:${VERSION}
    postCommit: {}
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: "1"
        memory: 1Gi
    runPolicy: SerialLatestOnly
    source:
      contextDir: base
      type: Binary
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: ${NAME}-base:v1
      type: Docker
    successfulBuildsHistoryLimit: 2
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
parameters:
- description: A name used for all objects
  displayName: Name
  name: NAME
  required: true
  value: jenkins-atomic
- description: A name suffix used for all objects
  displayName: Suffix
  name: SUFFIX
  required: false
  value: ""
- description: A version used for the image tags
  displayName: version
  name: VERSION
  required: true
  value: v1.0.0
